import streamlit as st
from openai import OpenAI

client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])

def generate_captions(description):
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a creative assistant that writes photo captions."},
            {"role": "user", "content": description}
        ],
        max_tokens=250
    )
    return response.choices[0].message.content.strip()

st.set_page_config(page_title="Caption Assistant", page_icon="🖼️")
st.title("🖼️ AI Caption Assistant")
st.write("Enter a description and get a caption generated by AI!")

description_input = st.text_area("Describe your image or context:", height=150)

if st.button("Generate Caption"):
    if description_input.strip():
        with st.spinner("Generating your caption..."):
            try:
                result = generate_captions(description_input)
                st.success("✅ Caption generated!")
                st.markdown(f"**💬 {result}**")
            except Exception as e:
                st.error(f"❌ Error: {str(e)}")
    else:
        st.warning("⚠️ Please enter a description.")
